- name: Tap FelixKratz/formulae with homebrew
  community.general.homebrew_tap:
    name: FelixKratz/formulae
    state: present

- name: Install JankyBorders with homebrew
  community.general.homebrew:
    name: borders
    state: present
